name: Add comment to PR

on:
  pull_request:
    type: opened

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add comment to PR
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.ASmQyaKn?O6G7oN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"This is an automated comment added by GitHub Actions.\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
